<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="4" passed="3" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2022-04-23T17:23:59 IST" name="Default suite" finished-at="2022-04-23T17:24:07 IST" duration-ms="7567">
    <groups>
    </groups>
    <test started-at="2022-04-23T17:23:59 IST" name="Default test" finished-at="2022-04-23T17:24:07 IST" duration-ms="7567">
      <class name="com.employee.testcases.TC_01_GetAllEmployees">
        <test-method is-config="true" signature="setup()[pri:0, instance:com.employee.testcases.TC_01_GetAllEmployees@6a400542]" started-at="2022-04-23T17:23:59 IST" name="setup" finished-at="2022-04-23T17:23:59 IST" duration-ms="15" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method is-config="true" signature="getAllEmployees()[pri:0, instance:com.employee.testcases.TC_01_GetAllEmployees@6a400542]" started-at="2022-04-23T17:23:59 IST" name="getAllEmployees" finished-at="2022-04-23T17:24:06 IST" duration-ms="7326" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getAllEmployees -->
        <test-method signature="checkContentType()[pri:0, instance:com.employee.testcases.TC_01_GetAllEmployees@6a400542]" started-at="2022-04-23T17:24:06 IST" name="checkContentType" finished-at="2022-04-23T17:24:06 IST" duration-ms="27" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- checkContentType -->
        <test-method signature="checkResponseBody()[pri:0, instance:com.employee.testcases.TC_01_GetAllEmployees@6a400542]" started-at="2022-04-23T17:24:06 IST" name="checkResponseBody" finished-at="2022-04-23T17:24:07 IST" duration-ms="70" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- checkResponseBody -->
        <test-method signature="checkResponsetime()[pri:0, instance:com.employee.testcases.TC_01_GetAllEmployees@6a400542]" started-at="2022-04-23T17:24:07 IST" name="checkResponsetime" finished-at="2022-04-23T17:24:07 IST" duration-ms="12" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertTrue(Assert.java:45)
at org.testng.Assert.assertTrue(Assert.java:55)
at com.employee.testcases.TC_01_GetAllEmployees.checkResponsetime(TC_01_GetAllEmployees.java:47)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- checkResponsetime -->
        <test-method signature="checkStatusCode()[pri:0, instance:com.employee.testcases.TC_01_GetAllEmployees@6a400542]" started-at="2022-04-23T17:24:07 IST" name="checkStatusCode" finished-at="2022-04-23T17:24:07 IST" duration-ms="4" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- checkStatusCode -->
        <test-method is-config="true" signature="teardown()[pri:0, instance:com.employee.testcases.TC_01_GetAllEmployees@6a400542]" started-at="2022-04-23T17:24:07 IST" name="teardown" finished-at="2022-04-23T17:24:07 IST" duration-ms="3" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- teardown -->
      </class> <!-- com.employee.testcases.TC_01_GetAllEmployees -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
